/* Generated by tools/mesh_weaver_assets.py; edit its Blender source.
 * Physical metres, RF X-right/Y-up/+Z-front. Rotations use degrees.
 * No pivot correction or floor recentering is applied by the importer. */
#ifndef RF_MESH_WEAVER_LAYOUT_GENERATED_H
#define RF_MESH_WEAVER_LAYOUT_GENERATED_H

#define RF_MESH_WEAVER_HEAD_COUNT 8
struct rf_mesh_weaver_head_layout {
    double position_m[3];
    double yaw_degrees, idle_pitch_degrees;
    int column, lower;
};
static const struct rf_mesh_weaver_head_layout rf_mesh_weaver_heads[8] = {
    {{-0.5850969, 0.542, 0.5850969}, 135, -28, 0, 1},
    {{-0.5850969, 1.62, 0.5850969}, 135, 36, 0, 0},
    {{0.5850969, 0.542, 0.5850969}, -135, -28, 1, 1},
    {{0.5850969, 1.62, 0.5850969}, -135, 36, 1, 0},
    {{0.5850969, 0.542, -0.5850969}, -45, -28, 2, 1},
    {{0.5850969, 1.62, -0.5850969}, -45, 36, 2, 0},
    {{-0.5850969, 0.542, -0.5850969}, 45, -28, 3, 1},
    {{-0.5850969, 1.62, -0.5850969}, 45, 36, 3, 0},
};

static const double rf_mesh_weaver_core_position_in_yoke_m[3] = {0, 0, 0.015};
static const double rf_mesh_weaver_aperture_in_core_m[3] = {0, 0, 0.065};
static const double rf_mesh_weaver_petal_hinge_in_core_m[3] = {0, 0.064, 0.08};
static const double rf_mesh_weaver_petal_roll_degrees[3] = {0, 120, 240};
static const double rf_mesh_weaver_petal_open_axis[3] = {1, 0, 0};
static const double rf_mesh_weaver_optical_axis[3] = {0, 0, 1};
static const double rf_mesh_weaver_yaw_limit_degrees[2] = {-34, 34};
static const double rf_mesh_weaver_pitch_limit_degrees[2] = {-62, 62};
static const double rf_mesh_weaver_petal_closed_degrees = 0;
static const double rf_mesh_weaver_petal_open_degrees = -64;
static const double rf_mesh_weaver_aperture_radius_m = 0.026;
static const double rf_mesh_weaver_tray_position_m[3] = {0, 0.362, 0};
static const double rf_mesh_weaver_terminal_position_m[3] = {-0.57, 0.1, 0.93};
/* Contact plane uses the quantized RMESH surface, excluding the raised guards. */
static const double rf_mesh_weaver_tray_support_height_m = 0.073275862069;
static const double rf_mesh_weaver_tray_delivery_translation_m[3] = {0, 0, 0.205};
static const double rf_mesh_weaver_screen_in_terminal_m[3] = {0, 0.529, 0.066};
static const double rf_mesh_weaver_screen_normal[3] = {0, 0, 1};
#define RF_MESH_WEAVER_SCREEN_WIDTH_RFU 160
#define RF_MESH_WEAVER_SCREEN_HEIGHT_RFU 104
static const double rf_mesh_weaver_build_center_m[3] = {0, 0.965, 0};
static const double rf_mesh_weaver_manufacturing_bounds_m[2][3] = {{-0.51, 0.48, -0.51}, {0.51, 1.5, 0.51}};
static const double rf_mesh_weaver_frame_bounds_m[2][3] = {{-0.852, 0, -0.906}, {0.852, 1.77, 1.05}};

#endif
