/* Generated by tools/mesh_weaver_blueprints.py; do not edit. */
#ifndef RF_WEAVER_BLUEPRINTS_GENERATED_H
#define RF_WEAVER_BLUEPRINTS_GENERATED_H

#include "toy_game.h"
#include "toy_mesh_weaver.h"

#define RF_WEAVER_BLUEPRINT_OPEN_VOLUME 1u
#define RF_WEAVER_BLUEPRINT_INVALID_VOLUME 2u
#define RF_WEAVER_BLUEPRINT_SIZE_LIMIT 4u

struct rf_weaver_blueprint {
    struct toy_mesh_blueprint geometry;
    const char *id, *name, *model_path;
    const char *source_sha256, *runtime_sha256;
    unsigned exported_vertex_count, material_count;
    int manufacturable, size_supported;
    unsigned unsupported_reasons;
    const char *unsupported_reason;
};

static const struct rf_weaver_blueprint rf_weaver_blueprints[] = {
    {
        {TOY_GAME_WEAPON_AK, 528u, 968u, 2281167ULL, {52u, 285u, 881u}, 0ULL},
        "ak", "AK", "rasterfall/assets/models/ar_ak47.rmesh",
        "523c4ef895510fab2d8016730c8e9befc2e9eb32a516b3716310c47227869877", "60f7e6f18d5b0005cde5c5d849486ca7a9539adb03b50f962d17ae1e92a07d72",
        1978u, 3u, 1, 1,
        0u, ""
    },
    {
        {TOY_GAME_WEAPON_PISTOL, 596u, 1160u, 306137ULL, {28u, 149u, 204u}, 0ULL},
        "pistol", "Pistol", "rasterfall/assets/models/pg_glock1.rmesh",
        "abfcbaac54c0fbe9851ba0e835327dab3b1d3861da0a7b1dc01c198a47e7c412", "624e1a584d861b2c7d979cc7cb78b4e4b36ec2544dc822daf90ce621ffa8c377",
        1929u, 5u, 1, 1,
        0u, ""
    },
    {
        {TOY_GAME_WEAPON_SMG, 312u, 572u, 588008ULL, {35u, 222u, 267u}, 0ULL},
        "smg", "SMG", "rasterfall/assets/models/smg_mac10.rmesh",
        "9062eafee9f825a4cf7490623a85a306943e035ff017134a0b1e769236a55b16", "a6caa5528751f2a5857f4c5df4f1a47dfc267381e0584d0b8b59977284315db9",
        1005u, 4u, 1, 1,
        0u, ""
    },
    {
        {TOY_GAME_WEAPON_SHOTGUN, 368u, 700u, 2025400ULL, {58u, 182u, 1004u}, 0ULL},
        "shotgun", "Shotgun", "rasterfall/assets/models/sg_pump_action.rmesh",
        "f980e9bc2e8499afd1942c07473c57fb0a1e84cc33e637c9361c825191ae567d", "747a298628679800424d65b8b595a70af344b309a5a4751757abcee7ea017954",
        1381u, 3u, 1, 1,
        0u, ""
    },
    {
        {TOY_GAME_WEAPON_AWP, 930u, 1782u, 0ULL, {83u, 226u, 1119u}, 0ULL},
        "awp", "AWP", "rasterfall/assets/models/rf_AWP.rmesh",
        "5e1b3b0692d71fb64d80809f8aa1d2f4bb42708c3c5004f3bd791e399327fc09", "1c59b7ad00d5788317adbf66628d20e402674cbc9716ffdfbe5e55ca45f33252",
        3198u, 3u, 0, 0,
        5u, "open manufacturing mesh; does not fit the work volume at the manufacturing orientation"
    },
};

#define RF_WEAVER_BLUEPRINT_COUNT (sizeof(rf_weaver_blueprints) / sizeof(rf_weaver_blueprints[0]))

#endif
