#include "core.h"
#include "string.h"
#include "tlibc_everything.h"
#include "rasterfall_model.h"
#include "rasterfall_vmd.h"
#include "math.h"

static unsigned int u32(const unsigned char *p){return p[0]|p[1]<<8|p[2]<<16|p[3]<<24;}
static float f32(const unsigned char *p){union{unsigned int u;float f;}v;v.u=u32(p);return v.f;}

/* Deterministic CP932 decoding for the MMD vocabulary used by this spike.
 * Unknown names remain printable as '?' and are reported as missing. */
struct name_map{const char *hex;const char *utf8;};
static const struct name_map names[]={
 {"90c3e68d82cc836e83548393","静謐のハサン"},{"834f838b815b8375","グルーブ"},{"835a8393835e815b","センター"},{"8ef1","首"},{"894591ab8268826a","右足ＩＫ"},{"8db691ab8268826a","左足ＩＫ"},
 {"89459872","右腕"},{"8db69872","左腕"},{"8db698729d80","左腕捩"},{"8db68ee89d80","左手捩"},{"8db68ee88ef1","左手首"},
 {"894598729d80","右腕捩"},{"89458ee89d80","右手捩"},{"89458ee88ef1","右手首"},{"8db68ca8","左肩"},{"89458ca8","右肩"},
 {"8fe394bc9067","上半身"},{"8fe394bc906732","上半身2"},{"93aa","頭"},{"89ba94bc9067","下半身"},
 {"8db682d082b6","左ひじ"},{"894582d082b6","右ひじ"},{"8db691ab","左足"},{"894591ab","右足"},
 {"8db68fac8e778250","左小指１"},{"8db68fac8e778251","左小指２"},{"8db68fac8e778252","左小指３"},
 {"8db696f28e778250","左薬指１"},{"8db696f28e778251","左薬指２"},{"8db696f28e778252","左薬指３"},
 {"8db692868e778250","左中指１"},{"8db692868e778251","左中指２"},{"8db692868e778252","左中指３"},
 {"8db6906c8e778250","左人指１"},{"8db6906c8e778251","左人指２"},{"8db6906c8e778252","左人指３"},
 {"8db690658e77824f","左親指０"},{"8db690658e778250","左親指１"},{"8db690658e778251","左親指２"},
 {"89458fac8e778250","右小指１"},{"89458fac8e778251","右小指２"},{"89458fac8e778252","右小指３"},
 {"894596f28e778250","右薬指１"},{"894596f28e778251","右薬指２"},{"894596f28e778252","右薬指３"},
 {"894592868e778250","右中指１"},{"894592868e778251","右中指２"},{"894592868e778252","右中指３"},
 {"8945906c8e778250","右人指１"},{"8945906c8e778251","右人指２"},{"8945906c8e778252","右人指３"},
 {"894590658e77824f","右親指０"},{"894590658e778250","右親指１"},{"894590658e778251","右親指２"},
 {"8db682c882eb","左ひざ"},{"894582c882eb","右ひざ"},{"8db691ab82c982c1","左足首"},{"894591ab82c982c1","右足首"}
};
static int hexval(unsigned char c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:-1;}
static int decode_name(const unsigned char *raw,char *out){
 int i,j,n=0,bytes=0; unsigned char hex[32];
 while(bytes<15&&raw[bytes]){hex[bytes]=raw[bytes];bytes++;}
 for(i=0;i<(int)(sizeof(names)/sizeof(names[0]));i++){
  int len=(int)strlen(names[i].hex)/2,ok=len==bytes;
  for(j=0;ok&&j<len;j++)if(hexval(names[i].hex[j*2])<<4|hexval(names[i].hex[j*2+1])){}
  if(ok){for(j=0;j<len;j++){int a=hexval(names[i].hex[j*2]),b=hexval(names[i].hex[j*2+1]);if(hex[j]!=(unsigned char)(a*16+b)){ok=0;break;}}}
  if(ok){strcpy(out,names[i].utf8);return 0;}
 }
 for(i=0;i<bytes&&n<RASTERFALL_VMD_MAX_NAME-1;i++)out[n++]=(raw[i]>=32&&raw[i]<128)?raw[i]:'?';out[n]=0;return 1;
}
static int track_find(const struct rasterfall_vmd_clip*c,const char*n){int i;for(i=0;i<c->track_count;i++)if(!strcmp(c->tracks[i].name,n))return i;return -1;}
static int ms(int frame){return frame*1000/30;}

int rasterfall_vmd_load(struct rasterfall_vmd_clip*c,const char*path){
 int fd,size,got=0,n,i,j,t;unsigned char*b;struct stat st;
 if(!c||!path)return -1;memset(c,0,sizeof(*c));fd=__openat(AT_FDCWD,path,O_RDONLY,0);
 if(fd<0||__fstat(fd,&st)<0||st.st_size<54||st.st_size>64*1024*1024){if(fd>=0)__close(fd);return -1;}
 size=(int)st.st_size;b=tlibc_malloc(size);if(!b){__close(fd);return -1;}while(got<size&&(n=__read(fd,b+got,size-got))>0)got+=n;__close(fd);
 if(got!=size||memcmp(b,"Vocaloid Motion Data 0002",24)!=0||54+(long)u32(b+50)*111>size){tlibc_free(b);return -1;}
 c->version=2;c->use_bezier_interpolation=1;decode_name(b+30,c->model_name);c->motion_count=(int)u32(b+50);c->tracks=tlibc_malloc(RASTERFALL_VMD_MAX_BONES*sizeof(*c->tracks));if(!c->tracks){tlibc_free(b);return -1;}memset(c->tracks,0,RASTERFALL_VMD_MAX_BONES*sizeof(*c->tracks));
 /* Pass 1: names and per-track counts. */
 for(i=0;i<c->motion_count;i++){char name[RASTERFALL_VMD_MAX_NAME];const unsigned char*p=b+54+i*111;decode_name(p,name);t=track_find(c,name);if(t<0){if(c->track_count==RASTERFALL_VMD_MAX_BONES){tlibc_free(b);rasterfall_vmd_unload(c);return -1;}t=c->track_count++;strcpy(c->tracks[t].name,name);c->tracks[t].first_frame=0x7fffffff;c->tracks[t].target_bone=-1;c->tracks[t].is_ik=strstr(name,"ＩＫ")!=0;c->tracks[t].is_center=!strcmp(name,"センター");c->tracks[t].is_groove=!strcmp(name,"グルーブ");if(c->tracks[t].is_ik)c->ignored_ik_tracks++;}c->tracks[t].key_count++;}
 for(i=0;i<c->track_count;i++){c->tracks[i].keys=tlibc_malloc(c->tracks[i].key_count*sizeof(*c->tracks[i].keys));c->tracks[i].animation_keys=tlibc_malloc(c->tracks[i].key_count*sizeof(*c->tracks[i].animation_keys));if(!c->tracks[i].keys||!c->tracks[i].animation_keys){tlibc_free(b);rasterfall_vmd_unload(c);return -1;}c->tracks[i].key_count=0;}
 for(i=0;i<c->motion_count;i++){const unsigned char*p=b+54+i*111;char name[RASTERFALL_VMD_MAX_NAME];struct rasterfall_vmd_keyframe*k;int f;decode_name(p,name);t=track_find(c,name);k=&c->tracks[t].keys[c->tracks[t].key_count++];f=(int)u32(p+15);k->frame=f;k->tx=f32(p+19);k->ty=f32(p+23);k->tz=f32(p+27);k->rotation.x=f32(p+31);k->rotation.y=f32(p+35);k->rotation.z=f32(p+39);k->rotation.w=f32(p+43);k->rotation=rasterfall_animation_quat_normalize(k->rotation);memcpy(k->interpolation,p+47,64);if(f>c->max_frame)c->max_frame=f;if(f<c->tracks[t].first_frame)c->tracks[t].first_frame=f;if(f>c->tracks[t].last_frame)c->tracks[t].last_frame=f;if(k->tx||k->ty||k->tz)c->tracks[t].translation_changed=1;if(k->rotation.x||k->rotation.y||k->rotation.z||k->rotation.w<0.999f)c->tracks[t].rotation_changed=1;if(memcmp(k->interpolation,(unsigned char[64]){0},64))c->interpolation_tracks=1;}
 /* VMD files are not required to be ordered by bone/frame. */
 for(i=0;i<c->track_count;i++)for(j=1;j<c->tracks[i].key_count;j++){struct rasterfall_vmd_keyframe x=c->tracks[i].keys[j];int k=j-1;while(k>=0&&c->tracks[i].keys[k].frame>x.frame){c->tracks[i].keys[k+1]=c->tracks[i].keys[k];k--;}c->tracks[i].keys[k+1]=x;}
 for(i=0;i<c->track_count;i++)for(j=0;j<c->tracks[i].key_count;j++){c->tracks[i].animation_keys[j].time_ms=ms(c->tracks[i].keys[j].frame);c->tracks[i].animation_keys[j].rotation=c->tracks[i].keys[j].rotation;c->tracks[i].animation_keys[j].interpolation=c->tracks[i].keys[j].interpolation;}
 c->duration_ms=ms(c->max_frame);tlibc_free(b);return 0;
}
void rasterfall_vmd_unload(struct rasterfall_vmd_clip*c){int i;if(!c)return;for(i=0;i<c->track_count;i++){if(c->tracks[i].keys)tlibc_free(c->tracks[i].keys);if(c->tracks[i].animation_keys)tlibc_free(c->tracks[i].animation_keys);}if(c->tracks)tlibc_free(c->tracks);memset(c,0,sizeof(*c));}
void rasterfall_vmd_set_linear_interpolation(struct rasterfall_vmd_clip*c,int linear){if(c)c->use_bezier_interpolation=!linear;}
int rasterfall_vmd_map_eula(struct rasterfall_vmd_clip*c,const struct rasterfall_model_asset*a){int i,j,m=0;if(!c||!a)return -1;for(i=0;i<c->track_count;i++){struct rasterfall_vmd_bone_track*t=&c->tracks[i];t->target_bone=rasterfall_model_find_bone(a,t->name);t->mapping_status=t->target_bone<0?0:t->is_ik?2:1;for(j=0;j<i&&t->target_bone>=0;j++)if(c->tracks[j].target_bone==t->target_bone)t->mapping_status=3;if(t->mapping_status==1)m++;}return m;}
void rasterfall_vmd_dump(const struct rasterfall_vmd_clip*c,const struct rasterfall_model_asset*a){int i,m=0,d=0,ig=0,dup=0;if(!c)return;__printf("vmd: header=Vocaloid Motion Data 0002 version=%d model=\"%s\" bone_motions=%d unique_bones=%d max_frame=%d duration_ms=%d (30fps)\n",c->version,c->model_name,c->motion_count,c->track_count,c->max_frame,c->duration_ms);__printf("vmd: interpolation=%s runtime=%s IK tracks=%d status=IK tracks detected but ignored in v1\n",c->interpolation_tracks?"present":"not detected",c->use_bezier_interpolation?"VMD-BEZIER/NLERP":"LINEAR/NLERP",c->ignored_ik_tracks);for(i=0;i<c->track_count;i++){const struct rasterfall_vmd_bone_track*t=&c->tracks[i];const char*s=t->mapping_status==1?"exact":t->mapping_status==2?"ignored":t->mapping_status==3?"duplicate":"missing";if(t->mapping_status==1)m++;if(t->mapping_status==0)d++;if(t->mapping_status==2)ig++;if(t->mapping_status==3)dup++;__printf("  %-16s keys=%-3d frames=%d-%d translation=%s rotation=%s",t->name,t->key_count,t->first_frame,t->last_frame,t->translation_changed?"changes":"static",t->rotation_changed?"changes":"static");if(a)__printf(" -> %-16s [%s]",t->target_bone>=0?a->bones[t->target_bone].name:"-",s);__printf("\n");}if(a)__printf("mapping: mapped=%d missing=%d ignored=%d duplicate=%d coverage=%d/%d\n",m,d,ig,dup,m,c->track_count);}
static const struct rasterfall_vmd_bone_track *vmd_track(const struct rasterfall_vmd_clip*c,const char*n){int i;for(i=0;i<c->track_count;i++)if(!strcmp(c->tracks[i].name,n))return &c->tracks[i];return 0;}
static struct rasterfall_animation_quaternion vmd_sample(const struct rasterfall_vmd_bone_track*t,int time,int duration){const struct rasterfall_vmd_keyframe*a,*b;int i,factor=0;struct rasterfall_animation_quaternion q;if(!t||!t->key_count){q.x=q.y=q.z=0;q.w=1;return q;}if(duration>0)time%=duration;a=b=&t->keys[0];for(i=1;i<t->key_count;i++){if(time<t->keys[i].frame*1000/30){b=&t->keys[i];break;}a=&t->keys[i];}if(b!=a&&b->frame>a->frame)factor=(time-a->frame*1000/30)*1000/((b->frame-a->frame)*1000/30);if(a==&t->keys[t->key_count-1]&&duration>0&&time>a->frame*1000/30&&t->key_count>1){int nt=duration;if(nt>a->frame*1000/30)factor=(time-a->frame*1000/30)*1000/(nt-a->frame*1000/30);b=&t->keys[0];}if(factor<0)factor=0;if(factor>1000)factor=1000;return rasterfall_animation_quat_nlerp(a->rotation,b->rotation,factor);}
static double vmd_quat_angle(struct rasterfall_animation_quaternion a,struct rasterfall_animation_quaternion b){double d=a.x*b.x+a.y*b.y+a.z*b.z+a.w*b.w;if(d<0)d=-d;if(d>1)d=1;return 2*atan2(sqrt(1-d*d),d)*180.0/M_PI;}
static void vmd_axis_angle(struct rasterfall_animation_quaternion q){double n=sqrt(q.x*q.x+q.y*q.y+q.z*q.z),angle=2*atan2(n,q.w)*180.0/M_PI;__printf("q=(%.4f,%.4f,%.4f,%.4f) axis=(%.3f,%.3f,%.3f) angle=%.2f",q.x,q.y,q.z,q.w,n>0.000001?q.x/n:0,n>0.000001?q.y/n:0,n>0.000001?q.z/n:0,angle);}
static void vmd_dump_rotation_curve(const struct rasterfall_vmd_bone_track*t){const unsigned char*p;int i,curved=0,linear=0;if(!t||!t->key_count){__printf(" bezier=missing");return;}for(i=0;i<t->key_count;i++){p=t->keys[i].interpolation;if(p[3]==p[7]&&p[7]==p[11]&&p[11]==p[15])linear++;else curved++;}p=t->keys[0].interpolation;__printf(" rotation_bezier_first=(%d,%d,%d,%d) shape=%s segments=%d_curved/%d_linear-like",p[3],p[7],p[11],p[15],(p[3]==p[7]&&p[7]==p[11]&&p[11]==p[15])?"linear-like":"curved",curved,linear);}
void rasterfall_vmd_dump_motion_diagnostic(const struct rasterfall_vmd_clip*c,const struct rasterfall_model_asset*a){static const char*legs[]={"左足","右足","左ひざ","右ひざ","左足首","右足首","左足ＩＫ","右足ＩＫ"};static const char*upper[]={"頭","首","上半身","上半身2"};int i,p,period;struct rasterfall_humanoid_rest_basis basis[RASTERFALL_HUMANOID_BONE_COUNT];if(!c)return;period=c->max_frame>=90?c->max_frame/5:c->max_frame;__printf("vmd motion diagnosis: base_period_frames=%d (phase samples 0/25/50/75/100%%)\n",period);for(i=0;i<(int)(sizeof(legs)/sizeof(legs[0]));i++){const struct rasterfall_vmd_bone_track*t=vmd_track(c,legs[i]);if(!t){__printf("  %-8s ABSENT (no ordinary VMD bone track)\n",legs[i]);continue;}__printf("  %-8s track=present frames=%d-%d\n",legs[i],t->first_frame,t->last_frame);for(p=0;p<5;p++){int time=period*p*1000/4/30;__printf("    phase=%d%% ",p*25);vmd_axis_angle(vmd_sample(t,time,c->duration_ms));__printf("\n");}}
 if(a){__printf("eula leg basis:\n");for(i=0;i<6;i++){int bone=rasterfall_model_find_bone(a,legs[i]);int child=-1,j;__printf("  %-8s ",legs[i]);if(bone<0){__printf("missing\n");continue;}for(j=0;j<(int)a->bone_count;j++)if(a->bones[j].parent==bone){child=j;break;}__printf("index=%d parent=%d head=(%d,%d,%d)",bone,a->bones[bone].parent,a->bones[bone].rest_x,a->bones[bone].rest_y,a->bones[bone].rest_z);if(child>=0)__printf(" child=%s delta=(%d,%d,%d)",a->bones[child].name,a->bones[child].rest_x-a->bones[bone].rest_x,a->bones[child].rest_y-a->bones[bone].rest_y,a->bones[child].rest_z-a->bones[bone].rest_z);__printf("\n");}if(rasterfall_model_build_humanoid_bases(a,basis)==0){__printf("  anatomical axes: left/right leg swing candidate=third axis (approximately X); primary points down\n");__printf("    left_leg third=(%.3f,%.3f,%.3f) right_leg third=(%.3f,%.3f,%.3f)\n",basis[RASTERFALL_HUMANOID_LEFT_UPPER_LEG].third[0],basis[RASTERFALL_HUMANOID_LEFT_UPPER_LEG].third[1],basis[RASTERFALL_HUMANOID_LEFT_UPPER_LEG].third[2],basis[RASTERFALL_HUMANOID_RIGHT_UPPER_LEG].third[0],basis[RASTERFALL_HUMANOID_RIGHT_UPPER_LEG].third[1],basis[RASTERFALL_HUMANOID_RIGHT_UPPER_LEG].third[2]);}}
 __printf("head/torso sampling: dt=16ms, runtime=shortest-path nlerp\n");for(i=0;i<(int)(sizeof(upper)/sizeof(upper[0]));i++){const struct rasterfall_vmd_bone_track*t=vmd_track(c,upper[i]);double max=0;int max_time=0,duplicates=0,negative=0,j;int last_frame=-1;if(!t){__printf("  %-8s ABSENT\n",upper[i]);continue;}for(j=0;j<t->key_count;j++){if(t->keys[j].frame==last_frame)duplicates++;last_frame=t->keys[j].frame;if(j&&t->keys[j-1].rotation.x*t->keys[j].rotation.x+t->keys[j-1].rotation.y*t->keys[j].rotation.y+t->keys[j-1].rotation.z*t->keys[j].rotation.z+t->keys[j-1].rotation.w*t->keys[j].rotation.w<0)negative++;}for(j=0;j<c->duration_ms;j+=16){double angle=vmd_quat_angle(vmd_sample(t,j,c->duration_ms),vmd_sample(t,j+16<c->duration_ms?j+16:c->duration_ms-1,c->duration_ms));if(angle>max){max=angle;max_time=j;}}__printf("  %-8s max_step=%.3fdeg at=%dms velocity=%.2fdeg/s end_to_start=%.3fdeg duplicate_frames=%d negative_adjacent_dots=%d interpolation=curve-data",upper[i],max,max_time,max/.016,vmd_quat_angle(vmd_sample(t,c->duration_ms-1,c->duration_ms),vmd_sample(t,0,c->duration_ms)),duplicates,negative);vmd_dump_rotation_curve(t);__printf("\n");}
 __printf("diagnosis: ordinary leg tracks=%s; IK leg tracks=%s; direct v1 cannot produce authored thigh swing while IK is ignored\n",vmd_track(c,"左足")||vmd_track(c,"右足")?"present":"absent",vmd_track(c,"左足ＩＫ")&&vmd_track(c,"右足ＩＫ")?"present":"absent");}
int rasterfall_vmd_build_animation(const struct rasterfall_vmd_clip*v,struct rasterfall_animation_clip*c,struct rasterfall_animation_track*t,int cap){int i,n=0;if(!v||!c||!t)return-1;for(i=0;i<v->track_count&&n<cap;i++)if(v->tracks[i].target_bone>=0&&!v->tracks[i].is_ik){t[n].target_bone=v->tracks[i].target_bone;t[n].keys=v->tracks[i].animation_keys;t[n].key_count=v->tracks[i].key_count;n++;}c->duration_ms=v->duration_ms;c->loop=1;c->tracks=t;c->track_count=n;c->use_vmd_bezier=v->use_bezier_interpolation;return n;}
void rasterfall_vmd_sample_translation(const struct rasterfall_vmd_clip*v,int time_ms,int out[3]){int i,j;double t=0;float x=0,y=0,z=0;if(!out)return;out[0]=out[1]=out[2]=0;if(!v)return;if(v->duration_ms>0)time_ms%=v->duration_ms;for(i=0;i<v->track_count;i++)if(v->tracks[i].is_center||v->tracks[i].is_groove){const struct rasterfall_vmd_bone_track*q=&v->tracks[i];const struct rasterfall_vmd_keyframe*a=&q->keys[0],*b=a;for(j=1;j<q->key_count;j++){if(time_ms<q->keys[j].frame*1000/30){b=&q->keys[j];break;}a=&q->keys[j];}if(b!=a&&b->frame>a->frame)t=(time_ms-a->frame*1000/30)/(double)((b->frame-a->frame)*1000/30);x+=(float)(a->tx+(b->tx-a->tx)*t);y+=(float)(a->ty+(b->ty-a->ty)*t);z+=(float)(a->tz+(b->tz-a->tz)*t);}out[0]=(int)(x*232.0f);out[1]=(int)(y*232.0f);out[2]=(int)(z*232.0f);}
int rasterfall_vmd_logic_test(void){struct rasterfall_animation_quaternion q={1,2,3,4};unsigned char curve[64];int linear,curved;memset(curve,0,sizeof(curve));curve[3]=20;curve[7]=8;curve[11]=107;curve[15]=119;linear=rasterfall_animation_vmd_bezier_factor(curve,500);if(linear==500)return 1;curved=rasterfall_animation_vmd_bezier_factor(curve,linear);if(curved<0||curved>1000)return 2;curve[3]=255;if(rasterfall_animation_vmd_bezier_factor(curve,500)!=500)return 3;q=rasterfall_animation_quat_normalize(q);return q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w<.999||q.x*q.x+q.y*q.y+q.z*q.z+q.w*q.w>1.001?4:0;}
