#!/usr/bin/env python3
"""Author the Frontier Station 01 spatial map; mission state lives in Game.

All authored coordinates below are metres, east +X and north +Z. Stable region
and object names are the binding boundary for session and mission configuration.
Run without --write to check that the checked-in map matches its source.
"""
import argparse
import math
from pathlib import Path

from lab_computer import generate as computer

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "rasterfall/assets/maps/frontier_station_01.map"


def rfu(value):
    return round(value * 512)


def generate():
    lines = ["# Frontier Station 01. Generated by tools/frontier_station_map.py.",
             "# Spatial facts only. East +X, north +Z; 512 RFU = 1 metre.",
             "map version=1 units=rfu",
             "world min_x=-29696 max_x=29696 min_z=-15360 max_z=49152 room_limit=50000 attr.identity=frontier_station_01"]
    floor_layers=[]

    def add(line):
        lines.append(line)

    def bounds(x0, x1, z0, z1):
        return f"min_x={rfu(x0)} max_x={rfu(x1)} min_z={rfu(z0)} max_z={rfu(z1)}"

    def region(name, kind, x, z, width=0, depth=0, attrs=""):
        add(f"region id={name} kind={kind} {bounds(x-width/2,x+width/2,z-depth/2,z+depth/2)}{attrs}")

    def obj(name, kind, x, z, yaw=0, y=0, scale=1000, collision=True, attrs=""):
        add(f"object id={name} kind={kind} x={rfu(x)} y={rfu(y)} z={rfu(z)} yaw={yaw} scale={scale} attr.collision={'component' if collision else 'none'}{attrs}")

    def box(name, x0, x1, z0, z1, height, walkable=False, visible=False, color="64717A"):
        add(f"collision id={name} shape=box {bounds(x0,x1,z0,z1)} height={rfu(height)} collision=true visible={str(visible).lower()} walkable={str(walkable).lower()} color={color}")

    def paint(name, x0, x1, z0, z1, color, style=0):
        floor_layers.append((name,rfu(x0),rfu(x1),rfu(z0),rfu(z1),color,style))

    def write_floor_partition():
        # Last-authored material wins during authoring. Runtime receives a
        # disjoint rectangular partition, never stacked coplanar floor meshes.
        xs=sorted({v for row in floor_layers for v in row[1:3]})
        zs=sorted({v for row in floor_layers for v in row[3:5]})
        active={};result=[]
        for z0,z1 in zip(zs,zs[1:]):
            runs=[]
            for x0,x1 in zip(xs,xs[1:]):
                owner=next((row for row in reversed(floor_layers)
                            if row[1]<=x0 and row[2]>=x1 and row[3]<=z0 and row[4]>=z1),None)
                if owner is None:continue
                key=(owner[0],owner[5],owner[6])
                if runs and runs[-1][0]==key and runs[-1][2]==x0:
                    runs[-1]=(key,runs[-1][1],x1)
                else:runs.append((key,x0,x1))
            new_active={}
            for key,x0,x1 in runs:
                identity=(key,x0,x1)
                if identity in active:
                    rect=active.pop(identity);rect[3]=z1
                else:rect=[x0,x1,z0,z1,key]
                new_active[identity]=rect
            result.extend(active.values());active=new_active
        result.extend(active.values())
        add("\n# Disjoint material partition: no overlapping floor paint planes.")
        counts={}
        for x0,x1,z0,z1,(name,color,style) in result:
            counts[name]=counts.get(name,0)+1
            add(f"render id={name}_{counts[name]} kind=floor min_x={x0} max_x={x1} min_z={z0} max_z={z1} height=0 color={color}"+(f" attr.style={style}" if style else ""))

    def sign(name, x, z, text, width=4, y=2.1, height=.65, color="C2D2D8", facing="-z"):
        add(f"render id={name} kind=sign {bounds(x-width/2,x+width/2,z,z)} height={rfu(y)-900} color={color} attr.height2={rfu(y+height)-900} attr.style=1 attr.text={text} attr.facing={facing}")

    def wall(name, x0, z0, x1, z1):
        length = abs(x1-x0)+abs(z1-z0)
        if length <= 0:
            return
        obj(name, "boundary_wall", (x0+x1)/2, (z0+z1)/2,
            yaw=0 if x0!=x1 else 90, attrs=f" attr.length={rfu(length)}")

    def door_wall(name, x0,z0,x1,z1,door_center):
        # Canonical door: 6 m overall, true 4.8 m x 3.6 m opening.
        if z0==z1:
            wall(name+"_a",x0,z0,door_center-3,z1)
            obj(name+"_door","arch_doorway",door_center,z0)
            wall(name+"_b",door_center+3,z0,x1,z1)
        else:
            wall(name+"_a",x0,z0,x1,door_center-3)
            obj(name+"_door","arch_doorway",x0,door_center,yaw=90)
            wall(name+"_b",x0,door_center+3,x1,z1)

    def fence(name,x0,z0,x1,z1):
        length=abs(x1-x0)+abs(z1-z0)
        count=math.ceil(length/6)
        step=length/count
        for i in range(count):
            fraction=(i+.5)/count
            obj(f"{name}_{i}","frontier_fence",x0+(x1-x0)*fraction,
                z0+(z1-z0)*fraction,yaw=0 if x0!=x1 else 90,
                scale=round(step/6*1000))

    add("\n# Session/mission binding anchors. No AI state or implicit spawns.")
    region("player_start","start",0,-16,attrs=" attr.sy=0 attr.cy=1024")
    region("frontier_spawn_north","mission_entry",-2,90,6,6," attr.role=frontier_infected_north")
    region("frontier_spawn_east","mission_entry",53,48,6,6," attr.role=frontier_infected_east")
    region("frontier_spawn_west","mission_entry",-53,38,6,6," attr.role=frontier_gunner_west")
    for route, points in {"north":[(-2,80),(-2,66),(0,43)],
                          "east":[(45,48),(39,43),(12,40)],
                          "west":[(-45,42),(-38,43),(-6,43)]}.items():
        for i,(x,z) in enumerate(points):
            region(f"frontier_route_{route}_{i}","mission_route",x,z,2,2,
                   f" attr.role=frontier_route_{route}")
    region("frontier_rally_courtyard","mission_route",0,31,4,4," attr.role=frontier_rally")
    guards = {"gate":[(-4,5),(9,4),(3,13)],
              "storage":[(-24,24),(-30,31),(-15,34)],
              "workshop":[(20,50),(28,59),(10,61)],
              "energy":[(-23,55),(-30,62),(-17,65)]}
    for zone, positions in guards.items():
        for i,(x,z) in enumerate(positions):
            region(f"frontier_guard_{zone}_{i}","mission_guard",x,z,
                   attrs=" attr.role=frontier_guard")
    region("frontier_station_bounds","mission_area",0,40,90,80," attr.role=frontier_station")

    add("\n# One continuous, navigable ground surface; paint only divides materials.")
    add("surface id=frontier_ground kind=ground min_x=-29696 max_x=29696 min_z=-15360 max_z=49152 height=0 material=777A6A attr.collision_id=frontier_ground_col")
    add("collision id=frontier_ground_col shape=flat min_x=-29696 max_x=29696 min_z=-15360 max_z=49152 height=0 collision=false visible=false walkable=true color=777A6A")
    paint("frontier_terrain",-58,58,-30,96,"777A6A")
    paint("frontier_yard",-45,45,0,80,"7B8585",12)
    paint("frontier_south_road",-6,6,-30,18,"515E65",11)
    paint("frontier_main_road",-6,6,18,96,"657079",11)
    paint("frontier_cross_road_w",-58,-6,39,47,"657079",11)
    paint("frontier_cross_road_e",6,58,39,47,"657079",11)
    paint("frontier_west_lane",-42,-37,0,39,"697677",11)
    paint("frontier_east_lane",38,43,0,39,"697677",11)
    paint("frontier_courtyard",-12,34,18,39,"909995")

    add("\n# South entry. Cover offsets the approach from the gate guards.")
    for i,(x,z,yaw) in enumerate([(-3,-20,0),(4,-12,0),(-8,-7,90),(7,10,0),(-7,17,0)]):
        obj(f"entry_cover_{i}","barrier",x,z,yaw=yaw)
    fence("south_fence_w",-45,0,-4,0)
    fence("south_fence_e",4,0,45,0)
    obj("entry_gate_w","industrial_pillar",-4.3,0,scale=1500)
    obj("entry_gate_e","industrial_pillar",4.3,0,scale=1500)
    # The 8 m opening remains free at all actor heights.
    obj("entry_gate_lintel_a","arch_beam",-2,0,y=4.2,scale=667,collision=False)
    obj("entry_gate_lintel_b","arch_beam",2,0,y=4.2,scale=667,collision=False)
    sign("entry_station_sign",0,-.22,"RF_/_01",width=5,y=4.22,height=.36)
    for i in range(7):
        paint(f"entry_crossing_{i}",-4.5+i*1.4,-3.8+i*1.4,-3,-1,"BBC3B8")
    # Gatehouse: real doorway, an offset visual barrier and a return console.
    wall("gatehouse_s",8,1,14,1)
    wall("gatehouse_e",14,1,14,7)
    wall("gatehouse_n",8,7,14,7)
    obj("gatehouse_door","arch_doorway",8,4,yaw=90)
    obj("gatehouse_desk","facility_desk",12,4,yaw=270)
    obj("gatehouse_monitor","facility_monitor",12,4,yaw=270,y=.75,collision=False)
    for i,z in enumerate([2.5,5.5]):
        obj(f"gatehouse_roof_{i}","frontier_canopy",11,z,y=4.2)
    obj("frontier_return_terminal","facility_terminal",7,-3,yaw=180)
    add("interaction id=frontier_return action=return_outpost x=3584 y=0 z=-2200")
    sign("frontier_return_sign",7,-3.2,"RETURN_RF",width=2.8,y=1.65,height=.4)

    add("\n# Warehouse: south loading door, east courtyard door and north rear door.")
    paint("storage_floor",-35,-13,22,38,"828C8C")
    door_wall("storage_s",-35,22,-13,22,-24)
    wall("storage_w",-35,22,-35,38)
    door_wall("storage_e",-13,22,-13,38,30)
    door_wall("storage_n",-35,38,-13,38,-24)
    sign("storage_sign",-24,21.75,"02_STORAGE",width=7,y=3.1,height=.65)
    for i,(x,z) in enumerate([(-29,26),(-29,34),(-17,26),(-17,35)]):
        obj(f"storage_pallet_{i}","crate",x,z)
        obj(f"storage_ammo_{i}","ammo_container",x,z,y=1,collision=False)
    for i,x in enumerate([-29,-27,-25]):
        obj(f"storage_compute_rack_{i}","research_compute_rack",x,36,yaw=180)
    obj("frontier_storage_terminal","research_terminal",-25,34)
    obj("storage_bench","workbench",-32,30,yaw=90)
    # Cargo rows leave a 10 m middle aisle and every door approach open.
    for i,z in enumerate([26,34]):
        obj(f"storage_rack_{i}","frontier_cargo_rack",-33.4,z,yaw=90)
    obj("storage_rack_e","frontier_cargo_rack",-14.5,25,yaw=90)
    # Side roof bays shelter stored goods; the central loading aisle is open
    # sky for crane access and remains directly selectable from RTS.
    for side,x in [("w",-33.5),("e",-14.5)]:
        for i,z in enumerate([25,31]):
            obj(f"storage_roof_{side}_{i}","frontier_canopy",x,z,yaw=90,y=4.2)
    obj("storage_loading_canopy","frontier_canopy",-24,21.5,y=4.2)
    for i,x in enumerate([-27.4,-20.6]):
        obj(f"storage_bollard_{i}","frontier_bollard",x,21)

    add("\n# Workshop: south loading door, west door, east flank and north service door.")
    paint("workshop_floor",6,34,48,68,"818C91")
    door_wall("workshop_s",6,48,34,48,20)
    door_wall("workshop_w",6,48,6,68,57)
    door_wall("workshop_e",34,48,34,68,57)
    door_wall("workshop_n",6,68,34,68,20)
    sign("workshop_sign",20,47.75,"01_WORKSHOP",width=8,y=3.1,height=.65)
    obj("frontier_workshop_terminal","research_terminal",18,54)
    obj("mesh_weaver","mesh_weaver_frame",23,58,collision=False)
    obj("mesh_weaver_service_links","mesh_weaver_service_links",23,58,collision=False)
    box("mesh_weaver_base_col",23-440/512,23+440/512,58-440/512,58+440/512,166/512,True)
    for i,(x,z) in enumerate([(-340,-340),(340,-340),(340,340),(-340,340)]):
        box(f"mesh_weaver_post_{i}",23+(x-45)/512,23+(x+45)/512,58+(z-45)/512,58+(z+45)/512,922/512)
    lines.extend(computer("frontier_workshop_computer",rfu(14),rfu(64),"frontier_workshop","79DDE8").strip().splitlines())
    obj("workshop_bench_w","workbench",9,51,yaw=90)
    obj("workshop_bench_n","workbench",28,65,yaw=180)
    for i,(x,z) in enumerate([(31,51),(31,64),(9,65)]):
        obj(f"workshop_supply_{i}","crate",x,z)
    # Peripheral roofed service bays, with a generous central skylight over
    # the real machine and the unit-command floor. No camera-dependent truth.
    for side,z in [("s",49.5),("n",66.5)]:
        for i,x in enumerate([9,15,21,27]):
            obj(f"workshop_roof_{side}_{i}","frontier_canopy",x,z,y=4.2)
    for side,x in [("w",7.5),("e",32.5)]:
        for i,z in enumerate([54,60]):
            obj(f"workshop_roof_{side}_{i}","frontier_canopy",x,z,yaw=90,y=4.2)
    obj("workshop_loading_canopy","frontier_canopy",20,47,y=4.2)
    for i,x in enumerate([16.6,23.4]):
        obj(f"workshop_bollard_{i}","frontier_bollard",x,47)

    add("\n# Energy compound: open work area, power hardware behind the capture console.")
    paint("energy_floor",-33,-15,54,68,"777F79",10)
    obj("frontier_energy_terminal","control_cabinet",-24,58)
    obj("energy_generator","frontier_collector",-25,64)
    for i,x in enumerate([-31,-29,-21,-19]):
        obj(f"energy_storage_{i}","control_cabinet",x,66,yaw=180)
    obj("energy_pipe_w","pipe_module",-31.5,59.5,yaw=90)
    obj("energy_pipe_e","pipe_module",-18,62,yaw=90)
    sign("energy_sign",-24,54,"03_ENERGY",width=6,y=2.3,height=.7)

    add("\n# Discontinuous courtyard cover: all groups retain an open retreat flank.")
    cover = [(-6,25,0),(5,29,0),(15,22,90),(23,34,0),(-9,35,90),
             (13,42,0),(-17,47,0),(-5,58,90),(38,63,90)]
    for i,(x,z,yaw) in enumerate(cover):
        obj(f"yard_cover_{i}","barrier",x,z,yaw=yaw)
    for i,(x,z) in enumerate([(-7,27),(16,24),(24,35),(-18,47),(37,27),(-39,17)]):
        obj(f"yard_crate_{i}","crate",x,z)
    for i,(x,z) in enumerate([(-10,3),(17,3),(-39,24),(38,24),(-10,46),(36,46),(-35,72),(30,73)]):
        obj(f"yard_lamp_{i}","lamp_post",x,z,yaw=0 if x<0 else 180)

    add("\n# Perimeter segments keep actual openings at the north, east and west roads.")
    fence("perimeter_w_s",-45,0,-45,38)
    fence("perimeter_w_n",-45,47,-45,80)
    fence("perimeter_e_s",45,0,45,43)
    fence("perimeter_e_n",45,53,45,80)
    fence("perimeter_n_w",-45,80,-6,80)
    fence("perimeter_n_e",6,80,45,80)
    # Outside blind corners screen arrivals without walling off their travel lane.
    wall("north_entry_screen",-10,85,-10,94)
    wall("east_entry_screen",50,55,57,55)
    wall("west_entry_screen",-57,32,-49,32)
    add("\n# Sparse grounded outcrops give the abandoned edge a finite silhouette.")
    for i,(x,z,yaw,scale) in enumerate([(-20,-15,20,1400),(23,-20,125,2000),
            (-40,-12,75,1600),(41,-15,15,1300),(-52,15,210,1800),
            (52,20,135,1500),(-52,64,12,2100),(52,71,93,1700),
            (-31,90,173,1800),(23,89,45,2300),(40,88,12,1400),(-18,83,75,1000)]):
        obj(f"terrain_rock_{i}","frontier_rock",x,z,yaw=yaw,scale=scale)
    write_floor_partition()
    return "\n".join(lines)+"\n"


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write",action="store_true")
    args=parser.parse_args()
    content=generate()
    if args.write:
        OUTPUT.write_text(content,encoding="utf-8",newline="\n")
        print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(content.splitlines())} lines)")
    else:
        if OUTPUT.read_text(encoding="utf-8")!=content:
            raise SystemExit("Map differs from generator; inspect before overwriting.")
        print("Frontier Station 01 map matches its source.")


if __name__=="__main__":
    main()
